version: '3'

services:

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: myapppass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  nats:
    image: nats:2.3
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always

volumes:
  redis-data:
  postgres-data:
